In [2]:
import pandas as pd
import numpy as np
pd.set_option("display.max_columns", None)

In [3]:
df = pd.read_csv("hr_raw_data.csv")

df

Unnamed: 0 age attrition businesstravel    dailyrate  \
0              0  51        No            NaN  2015.722222   
1              1  52        No            NaN  2063.388889   
2              2  42        No  travel_rarely  1984.253968   
3              3  47        No  travel_rarely  1771.404762   
4              4  46        No            NaN  1582.771346   
...          ...  ..       ...            ...          ...   
1673        1673  43        No            NaN   488.944444   
1674        1674  47        No            NaN  1973.984127   
1675        1675  29        No  travel_rarely   290.035510   
1676        1676  47        No  travel_rarely  1032.487286   
1677        1677  32        No            NaN   556.256661   

                    department  distancefromhome  education    educationfield  \
0                          NaN                 6          3               NaN   
1                          NaN                 1          4     Life Sciences   
2      Research & Development                  4          2  Technical Degree   
3                          NaN                 2          4           Medical   
4                          NaN                 3          3  Technical Degree   
...                        ...               ...        ...               ...   
1673                       NaN               -26          3           Medical   
1674                       NaN                26          4               NaN   
1675                       NaN                15          3               NaN   
1676                       NaN                 4          3     Life Sciences   
1677                       NaN                 2          2     Life Sciences   

      employeecount  employeenumber  environmentsatisfaction  gender  \
0                 1               1                        1       0   
1                 1               2                        3       0   
2                 1               3                        3       0   
3                 1               4                        1       1   
4                 1               5                        1       1   
...             ...             ...                      ...     ...   
1673              1             824                        2       1   
1674              1            1087                        4       1   
1675              1             528                        3       0   
1676              1              76                        3       1   
1677              1             401                        4       1   

      hourlyrate  jobinvolvement  joblevel                   jobrole  \
0            NaN               3         5        resEArch DIREcToR    
1            NaN               2         5                  ManAGeR    
2            NaN               3         5                  ManaGER    
3            NaN               3         4        ReseArCH DIrECtOr    
4            NaN               4         4          sAleS EXECUtIve    
...          ...             ...       ...                       ...   
1673         NaN               4         1       rESEaRcH SciEnTiST    
1674         NaN               3         5                  mANager    
1675         NaN               3         1       reSearch sCienTiSt    
1676         NaN               2         3   maNufACTURING DIREctOr    
1677   69.532083               3         2       resEArch scIENTisT    

      jobsatisfaction maritalstatus monthlyincome monthlyrate  \
0                   3           NaN     16280,83$   42330,17$   
1                   3           NaN           NaN   43331,17$   
2                   4       Married           NaN   41669,33$   
3                   3       Married     14307,50$   37199,50$   
4                   1      Divorced     12783,92$   33238,20$   
...               ...           ...           ...         ...   
1673                3        Single      3949,17$   10267,83$   
1674                3       Married   

# 2. EDA (Laura, ignora esto, ve directamente a punto 2)

In [4]:
df.duplicated().any() # Si hay duplicados, los devuelve

np.False_

In [5]:
duplicados = df[df.duplicated(keep=False)] # Vemos que, efectivamente, no aparecen duplicados en todo el df.
duplicados_ordenados = duplicados.sort_values(by=list(df.columns)).reset_index(drop=True)
duplicados_ordenados

Empty DataFrame
Columns: [Unnamed: 0, age, attrition, businesstravel, dailyrate, department, distancefromhome, education, educationfield, employeecount, employeenumber, environmentsatisfaction, gender, hourlyrate, jobinvolvement, joblevel, jobrole, jobsatisfaction, maritalstatus, monthlyincome, monthlyrate, numcompaniesworked, over18, overtime, percentsalaryhike, performancerating, relationshipsatisfaction, standardhours, stockoptionlevel, totalworkingyears, trainingtimeslastyear, worklifebalance, yearsatcompany, yearsincurrentrole, yearssincelastpromotion, yearswithcurrmanager, sameasmonthlyincome, datebirth, salary, roledepartament, numberchildren, remotework]
Index: []

In [6]:
cols_zara = df.iloc[:, 11:21] 

In [7]:
cols_zara

environmentsatisfaction  gender  hourlyrate  jobinvolvement  joblevel  \
0                           1       0         NaN               3         5   
1                           3       0         NaN               2         5   
2                           3       0         NaN               3         5   
3                           1       1         NaN               3         4   
4                           1       1         NaN               4         4   
...                       ...     ...         ...             ...       ...   
1673                        2       1         NaN               4         1   
1674                        4       1         NaN               3         5   
1675                        3       0         NaN               3         1   
1676                        3       1         NaN               2         3   
1677                        4       1   69.532083               3         2   

                       jobrole  jobsatisfaction maritalstatus monthlyincome  \
0           resEArch DIREcToR                 3           NaN     16280,83$   
1                     ManAGeR                 3           NaN           NaN   
2                     ManaGER                 4       Married           NaN   
3           ReseArCH DIrECtOr                 3       Married     14307,50$   
4             sAleS EXECUtIve                 1      Divorced     12783,92$   
...                        ...              ...           ...           ...   
1673       rESEaRcH SciEnTiST                 3        Single      3949,17$   
1674                  mANager                 3       Married     15943,72$   
1675       reSearch sCienTiSt                 4           NaN           NaN   
1676   maNufACTURING DIREctOr                 2      Divorced      8339,32$   
1677       resEArch scIENTisT                 3        Single           NaN   

     monthlyrate  
0      42330,17$  
1      43331,17$  
2      41669,33$  
3      37199,50$  
4      33238,20$  
...          ...  
1673   10267,83$  
1674   41453,67$  
1675    6090,75$  
1676   21682,23$  
1677   11681,39$  

[1678 rows x 10 columns]

In [8]:
cols_zara.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1678 entries, 0 to 1677
Data columns (total 10 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   environmentsatisfaction  1678 non-null   int64  
 1   gender                   1678 non-null   int64  
 2   hourlyrate               411 non-null    float64
 3   jobinvolvement           1678 non-null   int64  
 4   joblevel                 1678 non-null   int64  
 5   jobrole                  1678 non-null   object 
 6   jobsatisfaction          1678 non-null   int64  
 7   maritalstatus            1003 non-null   object 
 8   monthlyincome            1189 non-null   object 
 9   monthlyrate              1678 non-null   object 
dtypes: float64(1), int64(5), object(4)
memory usage: 131.2+ KB


In [9]:
cols_zara.describe().T

count       mean        std        min        25%  \
environmentsatisfaction  1678.0   4.264005   6.912695   1.000000   2.000000   
gender                   1678.0   0.398689   0.489774   0.000000   0.000000   
hourlyrate                411.0  83.140768  57.272101  13.012897  36.254439   
jobinvolvement           1678.0   2.740763   0.710359   1.000000   2.000000   
joblevel                 1678.0   2.064362   1.099425   1.000000   1.000000   
jobsatisfaction          1678.0   2.743147   1.105172   1.000000   2.000000   

                               50%         75%         max  
environmentsatisfaction   3.000000    4.000000   49.000000  
gender                    0.000000    1.000000    1.000000  
hourlyrate               69.532083  116.987103  255.963294  
jobinvolvement            3.000000    3.000000    4.000000  
joblevel                  2.000000    3.000000    5.000000  
jobsatisfaction           3.000000    4.000000    4.000000

In [10]:
cols_zara.isna().sum()

environmentsatisfaction       0
gender                        0
hourlyrate                 1267
jobinvolvement                0
joblevel                      0
jobrole                       0
jobsatisfaction               0
maritalstatus               675
monthlyincome               489
monthlyrate                   0
dtype: int64

In [11]:
cols_zara.duplicated() # Por el momento no nos interesa que haya o no duplicados ya que los datos que tenemos en nuestras cols (cols_zara) en un principio no tendrían que ser de valor único.

0       False
1       False
2       False
3       False
4       False
        ...  
1673     True
1674     True
1675     True
1676     True
1677     True
Length: 1678, dtype: bool

In [12]:
cols_zara[cols_zara.duplicated(keep=False)] # Devuelve todos los registros duplicados. Los hay porque esto es solo un fragmento del dataset completo (no es alarmante).

environmentsatisfaction  gender  hourlyrate  jobinvolvement  joblevel  \
8                           2       1         NaN               3         4   
60                          4       0         NaN               3         2   
75                          3       1         NaN               2         3   
107                         2       1         NaN               4         3   
111                         2       1  129.060911               3         3   
...                       ...     ...         ...             ...       ...   
1673                        2       1         NaN               4         1   
1674                        4       1         NaN               3         5   
1675                        3       0         NaN               3         1   
1676                        3       1         NaN               2         3   
1677                        4       1   69.532083               3         2   

                       jobrole  jobsatisfaction maritalstatus monthlyincome  \
8                     mANAGEr                 1       Married     13829,17$   
60      lAboratORy TeChNiCiaN                 2        Single      4928,33$   
75     maNufACTURING DIREctOr                 2      Divorced      8339,32$   
107    maNufaCturing direcTOr                 1      Divorced      8339,32$   
111           SalES ExeCuTIVe                 4           NaN      8339,32$   
...                        ...              ...           ...           ...   
1673       rESEaRcH SciEnTiST                 3        Single      3949,17$   
1674                  mANager                 3       Married     15943,72$   
1675       reSearch sCienTiSt                 4           NaN           NaN   
1676   maNufACTURING DIREctOr                 2      Divorced      8339,32$   
1677       resEArch scIENTisT                 3        Single           NaN   

     monthlyrate  
8      35955,83$  
60     12813,67$  
75     21682,23$  
107    21682,23$  
111    21682,23$  
...          ...  
1673   10267,83$  
1674   41453,67$  
1675    6090,75$  
1676   21682,23$  
1677   11681,39$  

[128 rows x 10 columns]

In [13]:
cols_zara["environmentsatisfaction"].value_counts()

environmentsatisfaction
4     483
3     471
2     316
1     306
12      7
35      7
13      6
14      6
47      5
24      5
41      4
42      4
46      4
36      4
48      4
20      3
22      3
11      3
18      3
45      3
27      3
25      3
17      3
37      2
38      2
16      2
31      2
15      2
19      2
29      2
28      1
33      1
21      1
39      1
49      1
10      1
26      1
43      1
Name: count, dtype: int64

In [14]:
cols_zara["environmentsatisfaction"].unique()

array([ 1,  3,  4,  2, 42, 37, 35, 25, 27, 31, 39, 21, 15, 14, 33, 19, 12,
       13, 28, 47, 36, 29, 24, 46, 16, 22, 41, 49, 11, 48, 18, 10, 45, 38,
       17, 20, 26, 43])

In [15]:
cols_zara["environmentsatisfaction"].min()

np.int64(1)

In [16]:
cols_zara["environmentsatisfaction"].max()

np.int64(49)

In [17]:
cols_zara["gender"].unique()

array([0, 1])

In [18]:
cols_zara["hourlyrate"].unique()

array([         nan,  69.53208262, 172.84325397, 216.04761905,
        79.97321429, 129.06091077, 246.74801587, 207.17460317,
        60.8859127 ,  36.25443872, 139.99503968,  86.24107143,
       197.84641831,  61.06646825, 245.62003968, 123.97718254,
       148.44246032, 255.96329365, 134.41071429,  71.92559524,
       113.78869048, 175.10019841, 247.49007937, 220.83234127,
        91.34821429,  37.77480159, 198.9593254 , 124.05456349,
       247.58035714, 108.48809524,  43.17857143,  68.46924603,
        32.48710317,  55.26289683,  83.46825397,  79.26388889,
        72.28670635,  45.96428571,  31.66170635,  65.19345238,
        52.24503968, 143.9156746 , 113.40178571, 143.19345238,
       139.86607143,  70.57142857,  97.04861111,  45.02281746,
       223.47619048, 134.9781746 ,  74.40178571,  67.14087302,
        58.06150794,  35.05357143,  73.18948413, 164.33134921,
        43.53968254,  54.79861111, 252.59722222,  83.81646825,
        46.71230159,  33.00297619,  70.77777778,  69.23

In [19]:
cols_zara["jobinvolvement"].unique()

array([3, 2, 4, 1])

In [20]:
cols_zara["joblevel"].unique()

array([5, 4, 3, 2, 1])

In [21]:
cols_zara["jobrole"].unique()

array([' resEArch DIREcToR ', ' ManAGeR ', ' ManaGER ', ...,
       ' sAlES ExECUTivE ', ' SaLes ExecUtIVe ',
       ' mAnUfactURInG DiRECTOr '], shape=(1579,), dtype=object)

In [22]:
cols_zara["jobsatisfaction"].unique()

array([3, 4, 1, 2])

In [23]:
cols_zara["maritalstatus"].unique()

array([nan, 'Married', 'Divorced', 'Single', 'divorced', 'Marreid'],
      dtype=object)

In [24]:
cols_zara["monthlyincome"].unique()

array(['16280,83$', nan, '14307,50$', '12783,92$', '14311,67$',
       '8339,32$', '13829,17$', '15943,72$', '16644,17$', '15034,17$',
       '16038,33$', '4492,84$', '8956,67$', '5167,50$', '3334,17$',
       '8705,83$', '2675,00$', '8555,00$', '8729,17$', '3934,17$',
       '3845,83$', '14132,50$', '8588,33$', '4505,00$', '4918,33$',
       '4928,33$', '5538,33$', '11100,00$', '5572,50$', '11560,00$',
       '15870,83$', '13345,83$', '8010,83$', '3588,33$', '14205,00$',
       '4222,50$', '3076,67$', '2342,59$', '4789,17$', '8685,00$',
       '5289,17$', '1956,67$', '10408,33$', '6683,33$', '7452,50$',
       '16060,00$', '4647,50$', '2242,50$', '6169,17$', '7352,50$',
       '2982,50$', '14815,83$', '15177,50$', '15991,67$', '15989,17$',
       '8340,00$', '6656,67$', '5902,50$', '3935,83$', '2839,17$',
       '2440,83$', '10025,83$', '12855,83$', '5135,00$', '4271,67$',
       '8015,83$', '4175,00$', '15860,83$', '8666,67$', '2327,50$',
       '4728,33$', '7010,00$', '2790,00$', '4

In [25]:
cols_zara["monthlyrate"].unique()

array(['42330,17$', '43331,17$', '41669,33$', '37199,50$', '33238,20$',
       '37210,33$', '21682,23$', '11681,39$', '35955,83$', '41453,67$',
       '43274,83$', '29037,67$', '28613,00$', '42347,50$', '39088,83$',
       '41699,67$', '23287,33$', '36296,00$', '13435,50$', '42997,50$',
       '8668,83$', '22635,17$', '34805,33$', '6955,00$', '22243,00$',
       '22695,83$', '13351,00$', '10228,83$', '6090,75$', '9999,17$',
       '36744,50$', '22329,67$', '11713,00$', '12787,67$', '23519,17$',
       '12813,67$', '14399,67$', '30274,83$', '28860,00$', '14488,50$',
       '10259,17$', '30056,00$', '41264,17$', '34699,17$', '20828,17$',
       '24938,33$', '9329,67$', '36933,00$', '10978,50$', '7999,33$',
       '43001,83$', '5000,67$', '12451,83$', '22581,00$', '13751,83$',
       '5087,33$', '6656,00$', '27061,67$', '17376,67$', '36980,67$',
       '19376,50$', '41756,00$', '12083,50$', '5830,50$', '16039,83$',
       '19116,50$', '7754,50$', '38521,17$', '39461,50$', '29416,83$',
   

In [26]:
cols_zara["monthlyrate"].isna().any()

np.False_

In [27]:
cols_zara["monthlyincome"].isna().any()

np.True_

# 2. Limpieza de datos

In [28]:
cols_zara

environmentsatisfaction  gender  hourlyrate  jobinvolvement  joblevel  \
0                           1       0         NaN               3         5   
1                           3       0         NaN               2         5   
2                           3       0         NaN               3         5   
3                           1       1         NaN               3         4   
4                           1       1         NaN               4         4   
...                       ...     ...         ...             ...       ...   
1673                        2       1         NaN               4         1   
1674                        4       1         NaN               3         5   
1675                        3       0         NaN               3         1   
1676                        3       1         NaN               2         3   
1677                        4       1   69.532083               3         2   

                       jobrole  jobsatisfaction maritalstatus monthlyincome  \
0           resEArch DIREcToR                 3           NaN     16280,83$   
1                     ManAGeR                 3           NaN           NaN   
2                     ManaGER                 4       Married           NaN   
3           ReseArCH DIrECtOr                 3       Married     14307,50$   
4             sAleS EXECUtIve                 1      Divorced     12783,92$   
...                        ...              ...           ...           ...   
1673       rESEaRcH SciEnTiST                 3        Single      3949,17$   
1674                  mANager                 3       Married     15943,72$   
1675       reSearch sCienTiSt                 4           NaN           NaN   
1676   maNufACTURING DIREctOr                 2      Divorced      8339,32$   
1677       resEArch scIENTisT                 3        Single           NaN   

     monthlyrate  
0      42330,17$  
1      43331,17$  
2      41669,33$  
3      37199,50$  
4      33238,20$  
...          ...  
1673   10267,83$  
1674   41453,67$  
1675    6090,75$  
1676   21682,23$  
1677   11681,39$  

[1678 rows x 10 columns]

## 2.1. Limpieza variable maritalstatus

In [29]:
cols_zara["maritalstatus"].unique() # Vemos los valores únicos de la var.

array([nan, 'Married', 'Divorced', 'Single', 'divorced', 'Marreid'],
      dtype=object)

In [30]:
# Primero, cambiamos todos los valores a minúsculas:
cols_zara["maritalstatus"] = cols_zara["maritalstatus"].str.lower()

In [31]:
# Segundo, corregimos los valores en los que hemos observado errores: 
cols_zara["maritalstatus"]=cols_zara["maritalstatus"].str.replace("marreid", "married")

In [32]:
cols_zara["maritalstatus"].unique() # Comprobamos que ya no existe "marreid" como valor único. 

array([nan, 'married', 'divorced', 'single'], dtype=object)

In [33]:
cols_zara["maritalstatus"] = cols_zara["maritalstatus"].str.strip() # Espacios en blanco al inicio y final de cada valor en la columna "maritalstatus".

In [34]:
cols_zara["maritalstatus"]

0            NaN
1            NaN
2        married
3        married
4       divorced
          ...   
1673      single
1674     married
1675         NaN
1676    divorced
1677      single
Name: maritalstatus, Length: 1678, dtype: object

## 2.2. Limpieza variable jobrole

In [35]:
cols_zara["jobrole"]

0             resEArch DIREcToR 
1                       ManAGeR 
2                       ManaGER 
3             ReseArCH DIrECtOr 
4               sAleS EXECUtIve 
                  ...           
1673         rESEaRcH SciEnTiST 
1674                    mANager 
1675         reSearch sCienTiSt 
1676     maNufACTURING DIREctOr 
1677         resEArch scIENTisT 
Name: jobrole, Length: 1678, dtype: object

In [36]:
# Primero, cambiamos todos los valores a minúsculas
cols_zara["jobrole"] = cols_zara["jobrole"].str.lower()

In [37]:
# Segundo, quitamos los espacios en blanco al inicio y final de cada valor en la columna:
cols_zara["jobrole"] = cols_zara["jobrole"].str.strip()

In [38]:
cols_zara["jobrole"].unique() # Hacemos una última comprobación.

array(['research director', 'manager', 'sales executive',
       'manufacturing director', 'research scientist',
       'healthcare representative', 'laboratory technician',
       'sales representative', 'human resources'], dtype=object)

## 2.3 Limpieza variable gender

In [39]:
cols_zara["gender"]

0       0
1       0
2       0
3       1
4       1
       ..
1673    1
1674    1
1675    0
1676    1
1677    1
Name: gender, Length: 1678, dtype: int64

In [40]:
cols_zara["gender"].unique()

array([0, 1])

In [41]:
# Cambiamos valores 0=male y 1=female usando el método replace:
cols_zara["gender"] = cols_zara["gender"].replace({0: "male", 1: "female"})

In [42]:
cols_zara["gender"]

0         male
1         male
2         male
3       female
4       female
         ...  
1673    female
1674    female
1675      male
1676    female
1677    female
Name: gender, Length: 1678, dtype: object

## 2.4. Limpieza variable environmentsatisfaction

In [43]:
cols_zara["environmentsatisfaction"] # Vemos que los valores son de 1 a 49. Confirmamos con César que se trata de un error y la escala debe ser de 1 a 4.

0       1
1       3
2       3
3       1
4       1
       ..
1673    2
1674    4
1675    3
1676    3
1677    4
Name: environmentsatisfaction, Length: 1678, dtype: int64

In [44]:
# Primero pasamos la variable a string
cols_zara["environmentsatisfaction"] = cols_zara["environmentsatisfaction"].astype(str)

In [45]:
cols_zara["environmentsatisfaction"].dtype # Comprobamos que la transformación se ha realizado correctamente.

dtype('O')

In [46]:
# Luego, usamos regex para cambiar cualquier valor que empieza por el número de la escala a ese mismo número. Así, los valores que comienzan por 1 (12, 16, etc.) se transforman a 1, y así de manera sucesiva con los demás números.
cols_zara["environmentsatisfaction"] = cols_zara["environmentsatisfaction"].replace({r"^1": 1, r"^2": 2, r"^3": 3, r"^4": 4}, regex=True)

C:\Users\SOL\AppData\Local\Temp\ipykernel_17628\926327445.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  cols_zara["environmentsatisfaction"] = cols_zara["environmentsatisfaction"].replace({r"^1": 1, r"^2": 2, r"^3": 3, r"^4": 4}, regex=True)


In [47]:
# Hacemos una comprobación de los valores únicos:
cols_zara["environmentsatisfaction"].unique()

array([1, 3, 4, 2])

In [48]:
# Volvemos a pasar los valores a int:
cols_zara["environmentsatisfaction"] = cols_zara["environmentsatisfaction"].astype(int)

In [49]:
# Comprobamos el tipo de la var para asegurarnos de que sea int de nuevo.
cols_zara["environmentsatisfaction"].dtype

dtype('int64')

## 2.5. Limpieza variable hourlyrate

In [50]:
# Vemos que podemos sacar los valores de hourlyrate a partir de la variable dailyrate de df. Los valores disponibles nos indican que hourlyrate=dailyrate/8

In [51]:
cols_zara['dailyrate'] = df['dailyrate'] # Creamos una nueva columna en cols_zara a partir de la col dailyrate de df.

In [52]:
cols_zara[["dailyrate", "hourlyrate"]] # Comparamos las dos columnas para asegurarnos de que el patrón es el que detallábamos arriba (hourlyrate=dailyrate/8). 

dailyrate  hourlyrate
0     2015.722222         NaN
1     2063.388889         NaN
2     1984.253968         NaN
3     1771.404762         NaN
4     1582.771346         NaN
...           ...         ...
1673   488.944444         NaN
1674  1973.984127         NaN
1675   290.035510         NaN
1676  1032.487286         NaN
1677   556.256661   69.532083

[1678 rows x 2 columns]

In [53]:
cols_zara["dailyrate"].dtype # Comprobamos el tipo de var.

dtype('float64')

In [54]:
cols_zara["hourlyrate"].dtype # Comprobamos el tipo de var

dtype('float64')

In [55]:
cols_zara['hourlyrate'] = cols_zara['hourlyrate'].fillna(cols_zara['dailyrate'] / 8) # modificamos los nulos de la col hourlyrate a partir de los valores correspondientes de dailyrate dividido entre 8.

In [56]:
cols_zara[["hourlyrate", "dailyrate"]] # comparamos las dos columnas y vemos que los valores null de hourlyrate ahora contienen los datos según lo establecido arriba.

hourlyrate    dailyrate
0     251.965278  2015.722222
1     257.923611  2063.388889
2     248.031746  1984.253968
3     221.425595  1771.404762
4     197.846418  1582.771346
...          ...          ...
1673   61.118056   488.944444
1674  246.748016  1973.984127
1675   36.254439   290.035510
1676  129.060911  1032.487286
1677   69.532083   556.256661

[1678 rows x 2 columns]

In [57]:
# Redondeamos a 2 decimales:

cols_zara["hourlyrate"]=round(cols_zara["hourlyrate"], 2)
cols_zara["dailyrate"]=round(cols_zara["dailyrate"], 2)

In [58]:
# cols_zara = cols_zara.drop(columns='dailyrate') # borramos la columna dailyrate
# no se hace dado que usaremos la var en la limpieza de la siguiente var.

## 2.6. Limpieza variable monthlyrate

In [59]:
# No tiene valores nulos, vemos que concuerda con los valores de dailyrate, siguiendo el siguiente patrón: monthlyrate=dailyrate*21.
# No obstante, requiere limpieza (cambiar tipo de valores a float, quitar símbolo de dólar, y convertir comas en puntos).

In [60]:
cols_zara["monthlyrate"].sample(10)

1377     4788,33$
254     11681,39$
1519    13751,83$
706      6090,75$
1005     5655,00$
1084    11681,39$
210     14269,67$
778      9282,00$
1509    21682,23$
52      22329,67$
Name: monthlyrate, dtype: object

In [61]:
cols_zara["monthlyrate"].dtype # Comprobamos el tipo de var

dtype('O')

In [62]:
# Pasamos monthlyrate de object a float. Para ello, necesitamos quitar el símbulo del $ y cambiar las comas de los decimales a puntos.

cols_zara["monthlyrate"] = cols_zara["monthlyrate"].str.replace('$', '', regex=False)
cols_zara["monthlyrate"] = cols_zara["monthlyrate"].str.replace(',', '.', regex=False)
cols_zara['monthlyrate'] = cols_zara['monthlyrate'].astype(float)

In [63]:
# Aunque en un principio no parece necesario, redondeamos a 2 decimales:

cols_zara["monthlyrate"]=round(cols_zara["monthlyrate"], 2)

In [64]:
cols_zara = cols_zara.drop(columns='dailyrate') # Tras hacer las comprobaciones necesarias, borramos la columna dailyrate, dado que ya no la necesitamos en cols_zara.

## 2.7. Limpieza variable monthlyincome

In [65]:
# Tras explorar df, hemos visto que monthlyincome (y también sameasmonthlyincome)= salary / 12. Salary no está en cols_zara, así que es necesario copiarla de df.

In [66]:
cols_zara['salary'] = df['salary'] # Creamos la nueva variable en cols_zara a partir de la variable salary de df.

In [67]:
cols_zara[['monthlyincome', "salary"]] # Confirmamos la relación de las variables de acuerdo con lo detallado arriba.

monthlyincome      salary
0        16280,83$  195370,00$
1              NaN  199990,00$
2              NaN  192320,00$
3        14307,50$  171690,00$
4        12783,92$         NaN
...            ...         ...
1673      3949,17$         NaN
1674     15943,72$  191324,62$
1675           NaN   28111,13$
1676      8339,32$  100071,84$
1677           NaN   53914,11$

[1678 rows x 2 columns]

In [68]:
cols_zara['monthlyincome'].dtype # Vemos que la variable es de tipo objeto.

dtype('O')

In [69]:
cols_zara['salary'].dtype # Vemos que la variable es de tipo objeto.

dtype('O')

In [70]:
# Pasamos los valores de monthlyrate de object a float. Para ello, primero necesitamos quitar el símbilo del $ y cambiar las comas de los decimales a puntos.
cols_zara["monthlyincome"] = cols_zara["monthlyincome"].str.replace('$', '', regex=False)
cols_zara["monthlyincome"] = cols_zara["monthlyincome"].str.replace(',', '.', regex=False)
cols_zara['monthlyincome'] = cols_zara['monthlyincome'].astype(float)
cols_zara['monthlyincome']

0       16280.83
1            NaN
2            NaN
3       14307.50
4       12783.92
          ...   
1673     3949.17
1674    15943.72
1675         NaN
1676     8339.32
1677         NaN
Name: monthlyincome, Length: 1678, dtype: float64

In [71]:
# Pasamos los valores de salary de object a float. Para ello, primero necesitamos quitar el símbilo del $ y cambiar las comas de los decimales a puntos.
cols_zara["salary"] = cols_zara["salary"].str.replace('$', '', regex=False)
cols_zara["salary"] = cols_zara["salary"].str.replace(',', '.', regex=False)
cols_zara['salary'] = cols_zara['salary'].astype(float)
cols_zara['salary']

0       195370.00
1       199990.00
2       192320.00
3       171690.00
4             NaN
          ...    
1673          NaN
1674    191324.62
1675     28111.13
1676    100071.84
1677     53914.11
Name: salary, Length: 1678, dtype: float64

In [72]:
# Rellenamos los valores nulos de la columna 'monthlyincome' calculando el ingreso mensual como 'salary / 12'.
cols_zara['monthlyincome'] = np.where(cols_zara['monthlyincome'].isna(), cols_zara['salary'] / 12, cols_zara['monthlyincome'])

In [73]:
cols_zara[['monthlyincome', "salary"]]

monthlyincome     salary
0      16280.830000  195370.00
1      16665.833333  199990.00
2      16026.666667  192320.00
3      14307.500000  171690.00
4      12783.920000        NaN
...             ...        ...
1673    3949.170000        NaN
1674   15943.720000  191324.62
1675    2342.594167   28111.13
1676    8339.320000  100071.84
1677    4492.842500   53914.11

[1678 rows x 2 columns]

In [74]:
# Redondeamos a 2 decimales:

cols_zara["monthlyincome"]=round(cols_zara["monthlyincome"], 2)
cols_zara["salary"]=round(cols_zara["salary"], 2)

In [75]:
cols_zara = cols_zara.drop(columns='salary') # Borramos la col "salary", dado que ya no la necesitamos.

## 2.8. Limpieza variable joblevel

In [ ]:
# Se trata de una escala de 1 a 5. Nada que limpiar (confirmado con César).

0       5
1       5
2       5
3       4
4       4
       ..
1673    1
1674    5
1675    1
1676    3
1677    2
Name: joblevel, Length: 1678, dtype: int64

## 2.9. Limpieza variable jobsatisfaction 

In [77]:
# Escala con valores presentes de 1 a 4. Limpieza no necesaria a priori.

## 2.10. Limpieza variable jobinvolvement 

In [78]:
# Escala con valores presentes de 1 a 4. Limpieza no necesaria a priori.

In [79]:
cols_zara

environmentsatisfaction  gender  hourlyrate  jobinvolvement  joblevel  \
0                           1    male      251.97               3         5   
1                           3    male      257.92               2         5   
2                           3    male      248.03               3         5   
3                           1  female      221.43               3         4   
4                           1  female      197.85               4         4   
...                       ...     ...         ...             ...       ...   
1673                        2  female       61.12               4         1   
1674                        4  female      246.75               3         5   
1675                        3    male       36.25               3         1   
1676                        3  female      129.06               2         3   
1677                        4  female       69.53               3         2   

                     jobrole  jobsatisfaction maritalstatus  monthlyincome  \
0          research director                3           NaN       16280.83   
1                    manager                3           NaN       16665.83   
2                    manager                4       married       16026.67   
3          research director                3       married       14307.50   
4            sales executive                1      divorced       12783.92   
...                      ...              ...           ...            ...   
1673      research scientist                3        single        3949.17   
1674                 manager                3       married       15943.72   
1675      research scientist                4           NaN        2342.59   
1676  manufacturing director                2      divorced        8339.32   
1677      research scientist                3        single        4492.84   

      monthlyrate  
0        42330.17  
1        43331.17  
2        41669.33  
3        37199.50  
4        33238.20  
...           ...  
1673     10267.83  
1674     41453.67  
1675      6090.75  
1676     21682.23  
1677     11681.39  

[1678 rows x 10 columns]

In [80]:
cols_zara.to_csv("columnas11-20.csv", index=False)

In [82]:
cols_zara["maritalstatus"].isnull().sum()

np.int64(675)

In [83]:
df

Unnamed: 0 age attrition businesstravel    dailyrate  \
0              0  51        No            NaN  2015.722222   
1              1  52        No            NaN  2063.388889   
2              2  42        No  travel_rarely  1984.253968   
3              3  47        No  travel_rarely  1771.404762   
4              4  46        No            NaN  1582.771346   
...          ...  ..       ...            ...          ...   
1673        1673  43        No            NaN   488.944444   
1674        1674  47        No            NaN  1973.984127   
1675        1675  29        No  travel_rarely   290.035510   
1676        1676  47        No  travel_rarely  1032.487286   
1677        1677  32        No            NaN   556.256661   

                    department  distancefromhome  education    educationfield  \
0                          NaN                 6          3               NaN   
1                          NaN                 1          4     Life Sciences   
2      Research & Development                  4          2  Technical Degree   
3                          NaN                 2          4           Medical   
4                          NaN                 3          3  Technical Degree   
...                        ...               ...        ...               ...   
1673                       NaN               -26          3           Medical   
1674                       NaN                26          4               NaN   
1675                       NaN                15          3               NaN   
1676                       NaN                 4          3     Life Sciences   
1677                       NaN                 2          2     Life Sciences   

      employeecount  employeenumber  environmentsatisfaction  gender  \
0                 1               1                        1       0   
1                 1               2                        3       0   
2                 1               3                        3       0   
3                 1               4                        1       1   
4                 1               5                        1       1   
...             ...             ...                      ...     ...   
1673              1             824                        2       1   
1674              1            1087                        4       1   
1675              1             528                        3       0   
1676              1              76                        3       1   
1677              1             401                        4       1   

      hourlyrate  jobinvolvement  joblevel                   jobrole  \
0            NaN               3         5        resEArch DIREcToR    
1            NaN               2         5                  ManAGeR    
2            NaN               3         5                  ManaGER    
3            NaN               3         4        ReseArCH DIrECtOr    
4            NaN               4         4          sAleS EXECUtIve    
...          ...             ...       ...                       ...   
1673         NaN               4         1       rESEaRcH SciEnTiST    
1674         NaN               3         5                  mANager    
1675         NaN               3         1       reSearch sCienTiSt    
1676         NaN               2         3   maNufACTURING DIREctOr    
1677   69.532083               3         2       resEArch scIENTisT    

      jobsatisfaction maritalstatus monthlyincome monthlyrate  \
0                   3           NaN     16280,83$   42330,17$   
1                   3           NaN           NaN   43331,17$   
2                   4       Married           NaN   41669,33$   
3                   3       Married     14307,50$   37199,50$   
4                   1      Divorced     12783,92$   33238,20$   
...               ...           ...           ...         ...   
1673                3        Single      3949,17$   10267,83$   
1674                3       Married   

In [ ]:
# salario (daily rate) + 100% daily rate + 30% del total (el 200%)