In [ ]:
# nuestras librerias a utilizar
import pandas as pd
import numpy as np


# Configuración
# -----------------------------------------------------------------------
pd.set_option('display.max_columns', None) # para poder visualizar todas las columnas de los DataFrames

pd.set_option('display.max_rows', None) # para poder visualizar todas las filas de los DataFrames

In [2]:
df = pd.read_csv("hr_raw_data.csv", index_col=0)

In [3]:
df.head(2)

age attrition businesstravel    dailyrate department  distancefromhome  \
0  51        No            NaN  2015.722222        NaN                 6   
1  52        No            NaN  2063.388889        NaN                 1   

   education educationfield  employeecount  employeenumber  \
0          3            NaN              1               1   
1          4  Life Sciences              1               2   

   environmentsatisfaction  gender  hourlyrate  jobinvolvement  joblevel  \
0                        1       0         NaN               3         5   
1                        3       0         NaN               2         5   

               jobrole  jobsatisfaction maritalstatus monthlyincome  \
0   resEArch DIREcToR                 3           NaN     16280,83$   
1             ManAGeR                 3           NaN           NaN   

  monthlyrate  numcompaniesworked over18 overtime  percentsalaryhike  \
0   42330,17$                   7      Y       No                 13   
1   43331,17$                   0    NaN      NaN                 14   

  performancerating  relationshipsatisfaction standardhours  stockoptionlevel  \
0               3,0                         3     Full Time                 0   
1               3,0                         1           NaN                 1   

  totalworkingyears  trainingtimeslastyear worklifebalance  yearsatcompany  \
0               NaN                      5             3,0              20   
1              34,0                      5             3,0              33   

  yearsincurrentrole  yearssincelastpromotion  yearswithcurrmanager  \
0                NaN                       15                    15   
1                NaN                       11                     9   

  sameasmonthlyincome  datebirth      salary roledepartament  numberchildren  \
0           16280,83$       1972  195370,00$             NaN             NaN   
1                 NaN       1971  199990,00$             NaN             NaN   

  remotework  
0        Yes  
1          1

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1678 entries, 0 to 1677
Data columns (total 41 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   age                       1678 non-null   object 
 1   attrition                 1678 non-null   object 
 2   businesstravel            877 non-null    object 
 3   dailyrate                 1678 non-null   float64
 4   department                312 non-null    object 
 5   distancefromhome          1678 non-null   int64  
 6   education                 1678 non-null   int64  
 7   educationfield            904 non-null    object 
 8   employeecount             1678 non-null   int64  
 9   employeenumber            1678 non-null   int64  
 10  environmentsatisfaction   1678 non-null   int64  
 11  gender                    1678 non-null   int64  
 12  hourlyrate                411 non-null    float64
 13  jobinvolvement            1678 non-null   int64  
 14  joblevel     

In [5]:
df.columns

Index(['age', 'attrition', 'businesstravel', 'dailyrate', 'department',
       'distancefromhome', 'education', 'educationfield', 'employeecount',
       'employeenumber', 'environmentsatisfaction', 'gender', 'hourlyrate',
       'jobinvolvement', 'joblevel', 'jobrole', 'jobsatisfaction',
       'maritalstatus', 'monthlyincome', 'monthlyrate', 'numcompaniesworked',
       'over18', 'overtime', 'percentsalaryhike', 'performancerating',
       'relationshipsatisfaction', 'standardhours', 'stockoptionlevel',
       'totalworkingyears', 'trainingtimeslastyear', 'worklifebalance',
       'yearsatcompany', 'yearsincurrentrole', 'yearssincelastpromotion',
       'yearswithcurrmanager', 'sameasmonthlyincome', 'datebirth', 'salary',
       'roledepartament', 'numberchildren', 'remotework'],
      dtype='object')

In [6]:
# me tocan las columnas 31-40:
df.iloc[:, 31:41]

yearsatcompany yearsincurrentrole  yearssincelastpromotion  \
0                 20                NaN                       15   
1                 33                NaN                       11   
2                 22                NaN                       11   
3                 20                NaN                        5   
4                 19                NaN                        2   
...              ...                ...                      ...   
1673               3                NaN                        1   
1674               5                NaN                        1   
1675               6                NaN                        1   
1676              22                NaN                       14   
1677               8                NaN                        0   

      yearswithcurrmanager sameasmonthlyincome  datebirth      salary  \
0                       15           16280,83$       1972  195370,00$   
1                        9                 NaN       1971  199990,00$   
2                       15                 NaN       1981  192320,00$   
3                        6           14307,50$       1976  171690,00$   
4                        8           12783,92$       1977         NaN   
...                    ...                 ...        ...         ...   
1673                     2            3949,17$       1980         NaN   
1674                     0           15943,72$       1976  191324,62$   
1675                     5                 NaN       1994   28111,13$   
1676                    10            8339,32$       1976  100071,84$   
1677                     7                 NaN       1991   53914,11$   

                           roledepartament  numberchildren remotework  
0                                      NaN             NaN        Yes  
1                                      NaN             NaN          1  
2      ManaGER  -  Research & Development              NaN          1  
3                                      NaN             NaN      False  
4                                      NaN             NaN          0  
...                                    ...             ...        ...  
1673                                   NaN             NaN        Yes  
1674                                   NaN             NaN      False  
1675                                   NaN             NaN      False  
1676                                   NaN             NaN        Yes  
1677                                   NaN             NaN          0  

[1678 rows x 10 columns]

In [7]:
columnas31_40 = df.iloc[:, 31:41]

In [8]:
columnas31_40["yearsatcompany"].unique()

array([20, 33, 22, 19, 21, 18, 24, 31, 26, 16, 23, 15, 17, 32, 14, 13, 25,
       12, 11, 37, 40, 36, 27, 29, 10,  9, 30,  8,  7, 34,  6,  5,  4,  2,
        3,  1,  0])

In [9]:
columnas31_40["yearsatcompany"].unique().sum()

np.int64(680)

In [10]:
columnas31_40["yearsincurrentrole"].unique()

array([nan, '13,0', '12,0', '11,0', '7,0', '6,0', '4,0', '3,0', '2,0',
       '1,0', '0,0'], dtype=object)

"yearsincurrentrole" tiene NAN, números con decimales como str, con coma ("13,0"):

- necesario modificar a int pero mientras tengamos NAN serán float, 

- cambiar (",0" por ""), 

- pensar qué hacer con los NAN

In [11]:
columnas31_40["yearsincurrentrole"] = columnas31_40["yearsincurrentrole"].str.replace(",0", "")

In [ ]:
columnas31_40["yearsincurrentrole"].unique() # compruebo que sale bien; pte NAN y pasar a int

array([nan, '13', '12', '11', '7', '6', '4', '3', '2', '1', '0'],
      dtype=object)

In [13]:
df["yearssincelastpromotion"].unique()

array([15, 11,  5,  2,  4,  7,  0,  1, 13, 14,  8, 12,  3,  6, 10,  9])

In [14]:
df["yearswithcurrmanager"].unique()

array([15,  9,  6,  8,  7, 11, 10, 12,  4,  0,  5, 17,  2, 14,  1, 13,  3,
       16])

In [15]:
df["sameasmonthlyincome"].unique()

array(['16280,83$', nan, '14307,50$', '12783,92$', '14311,67$',
       '8339,32$', '13829,17$', '15943,72$', '16644,17$', '15034,17$',
       '16038,33$', '4492,84$', '8956,67$', '5167,50$', '3334,17$',
       '8705,83$', '2675,00$', '8555,00$', '8729,17$', '3934,17$',
       '3845,83$', '14132,50$', '8588,33$', '4505,00$', '4918,33$',
       '4928,33$', '5538,33$', '11100,00$', '5572,50$', '11560,00$',
       '15870,83$', '13345,83$', '8010,83$', '3588,33$', '14205,00$',
       '4222,50$', '3076,67$', '2342,59$', '4789,17$', '8685,00$',
       '5289,17$', '1956,67$', '10408,33$', '6683,33$', '7452,50$',
       '16060,00$', '4647,50$', '2242,50$', '6169,17$', '7352,50$',
       '2982,50$', '14815,83$', '15177,50$', '15991,67$', '15989,17$',
       '8340,00$', '6656,67$', '5902,50$', '3935,83$', '2839,17$',
       '2440,83$', '10025,83$', '12855,83$', '5135,00$', '4271,67$',
       '8015,83$', '4175,00$', '15860,83$', '8666,67$', '2327,50$',
       '4728,33$', '7010,00$', '2790,00$', '4

"sameasmonthlyincome" tiene NAN, números con decimales como str, con coma y "dolar$" ("16280,83$"):

- necesario modificar a int pero mientras tengamos NAN serán float, 

- cambiar ("," por "."), 

- cambiar ("$" por ""), 

- pensar qué hacer con los NAN

In [16]:
columnas31_40["sameasmonthlyincome"] = columnas31_40["sameasmonthlyincome"].str.replace(",", ".").str.replace("$", "")

In [17]:
columnas31_40["sameasmonthlyincome"]

0       16280.83
1            NaN
2            NaN
3       14307.50
4       12783.92
          ...   
1673     3949.17
1674    15943.72
1675         NaN
1676     8339.32
1677         NaN
Name: sameasmonthlyincome, Length: 1678, dtype: object

In [18]:
df["datebirth"].unique()

array([1972, 1971, 1981, 1976, 1977, 1975, 1964, 1982, 1967, 1985, 1968,
       1983, 1965, 1988, 1978, 1990, 1987, 1989, 1970, 1980, 1963, 1991,
       1986, 1974, 1984, 1973, 1979, 1993, 1994, 1992, 1969, 1966, 1996,
       1995, 1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005])

In [19]:
df["salary"].unique()

array(['195370,00$', '199990,00$', '192320,00$', '171690,00$', nan,
       '100071,84$', '53914,11$', '165950,00$', '199730,00$',
       '134020,00$', '132060,00$', '195450,00$', '180410,00$',
       '192460,00$', '107480,00$', '167520,00$', '62010,00$',
       '198450,00$', '40010,00$', '104470,00$', '191324,62$',
       '160640,00$', '32100,00$', '102660,00$', '104750,00$', '61620,00$',
       '47210,00$', '153407,07$', '28111,13$', '46150,00$', '169590,00$',
       '54060,00$', '59020,00$', '108550,00$', '59140,00$', '66460,00$',
       '139730,00$', '66870,00$', '47350,00$', '138720,00$', '190450,00$',
       '96130,00$', '115100,00$', '170460,00$', '36920,00$', '198470,00$',
       '23080,00$', '57470,00$', '104220,00$', '63470,00$', '23480,00$',
       '30720,00$', '124900,00$', '80200,00$', '170680,00$', '89430,00$',
       '192720,00$', '55770,00$', '26910,00$', '74030,00$', '88230,00$',
       '35790,00$', '177790,00$', '182130,00$', '135770,00$',
       '191900,00$', '171230,

"salary" tiene NAN, números con decimales como str, con coma y "dolar$" ("195370,00$"):

- necesario modificar a int pero mientras tengamos NAN serán float, 

- cambiar ("," por "."), 

- cambiar ("$" por ""), 

- pensar qué hacer con los NAN

In [102]:
columnas31_40["salary"] = columnas31_40["salary"].str.replace(",", ".").str.replace("$", "")

In [103]:
columnas31_40["salary"]

0       195370.00
1       199990.00
2       192320.00
3       171690.00
4             NaN
          ...    
1673          NaN
1674    191324.62
1675     28111.13
1676    100071.84
1677     53914.11
Name: salary, Length: 1678, dtype: object

In [104]:
df["roledepartament"].unique()

array([nan, ' ManaGER  -  Research & Development ',
       ' MANAger  -  Research & Development ',
       ' heaLtHcArE repResENtATiVe  -  Research & Development ',
       ' saLEs exEcutIVe  -  Sales ', ' Sales ExECuTIVe  -  Sales ',
       ' heALthCArE RePResEntaTIVe  -  Research & Development ',
       ' lABORAtOry tECHnIcIan  -  Research & Development ',
       ' ManufactUrINg DiReCTOr  -  Research & Development ',
       ' SaleS eXEcUtIVE  -  Sales ',
       ' HEaLthcaRe rEprEsEnTAtiVe  -  Research & Development ',
       ' rESeArCH sCientIST  -  Research & Development ',
       ' healTHCAre rePREseNtATiVE  -  Research & Development ',
       ' mANaGer  -  Research & Development ',
       ' HEAltHCaRe REPreseNTatIve  -  Research & Development ',
       ' SaLeS eXECUTivE  -  Sales ',
       ' reSeARCH SCIEnTiST  -  Research & Development ',
       ' ReSearch DiRecTOR  -  Research & Development ',
       ' resEaRCh SciEnTist  -  Research & Development ',
       ' hUmaN REsoUrCes  -  H

"roledepartament" tiene NAN, strings con espacios antes y después de la palabra, mayúsculas y minúsculas mezcladas (" saLEs exEcutIVe  -  Sales "):

- necesario modificar a str pero mientras tengamos NAN serán float, 

- cambiar todo a minúsculas con .str.lower(), 

- cambiar espacios en blanco .str.strip(), 

- pensar qué hacer con los NAN

In [105]:
columnas31_40["roledepartament"] = columnas31_40["roledepartament"].str.lower().str.strip()

In [106]:
columnas31_40["roledepartament"].unique()

array([nan, 'manager  -  research & development',
       'healthcare representative  -  research & development',
       'sales executive  -  sales',
       'laboratory technician  -  research & development',
       'manufacturing director  -  research & development',
       'research scientist  -  research & development',
       'research director  -  research & development',
       'human resources  -  human resources', 'manager  -  sales',
       'sales representative  -  sales', 'manager  -  human resources'],
      dtype=object)

In [107]:
columnas31_40["numberchildren"].unique()

array([nan])

"numberchildren" aparece sin datos: valorar si eliminar o solicitar datos a la empresa

In [108]:
columnas31_40["remotework"].unique()

array(['Yes', '1', 'False', '0', 'True'], dtype=object)

"remotework" tiene varios valores ("'Yes', '1', 'False', '0', 'True'") cuando debe ser ('Yes' o 'No'):

como no vemos correlación entre columnas que nos digan si '1', 'False', '0' o 'True' son 'Yes' o 'No', entendemos que '1' y 'True' son 'Yes' y 'False' y '0' son 'No'

es necesario:

- cambiar ("1" por "Yes"),

- cambiar ("True" por "Yes"),

- cambiar ("False" por "No"),

- cambiar ("0" por "No"), 

- pensar qué hacer con los NAN

In [109]:
columnas31_40["remotework"]

0         Yes
1           1
2           1
3       False
4           0
        ...  
1673      Yes
1674    False
1675    False
1676      Yes
1677        0
Name: remotework, Length: 1678, dtype: object

In [110]:
df["distancefromhome"]

0        6
1        1
2        4
3        2
4        3
        ..
1673   -26
1674    26
1675    15
1676     4
1677     2
Name: distancefromhome, Length: 1678, dtype: int64

In [111]:
columnas31_40["remotework"] = columnas31_40["remotework"].str.replace("1", "Yes").str.replace("True", "Yes").str.replace("0", "No").str.replace("False", "No")

In [112]:
columnas31_40["remotework"].unique()

array(['Yes', 'No'], dtype=object)

In [113]:
columnas31_40

yearsatcompany yearsincurrentrole  yearssincelastpromotion  \
0                 20                NaN                       15   
1                 33                NaN                       11   
2                 22                NaN                       11   
3                 20                NaN                        5   
4                 19                NaN                        2   
...              ...                ...                      ...   
1673               3                NaN                        1   
1674               5                NaN                        1   
1675               6                NaN                        1   
1676              22                NaN                       14   
1677               8                NaN                        0   

      yearswithcurrmanager sameasmonthlyincome  datebirth     salary  \
0                       15            16280.83       1972  195370.00   
1                        9                 NaN       1971  199990.00   
2                       15                 NaN       1981  192320.00   
3                        6            14307.50       1976  171690.00   
4                        8            12783.92       1977        NaN   
...                    ...                 ...        ...        ...   
1673                     2             3949.17       1980        NaN   
1674                     0            15943.72       1976  191324.62   
1675                     5                 NaN       1994   28111.13   
1676                    10             8339.32       1976  100071.84   
1677                     7                 NaN       1991   53914.11   

                         roledepartament  numberchildren remotework  
0                                    NaN             NaN        Yes  
1                                    NaN             NaN        Yes  
2     manager  -  research & development             NaN        Yes  
3                                    NaN             NaN         No  
4                                    NaN             NaN         No  
...                                  ...             ...        ...  
1673                                 NaN             NaN        Yes  
1674                                 NaN             NaN         No  
1675                                 NaN             NaN         No  
1676                                 NaN             NaN        Yes  
1677                                 NaN             NaN         No  

[1678 rows x 10 columns]

In [114]:
columnas31_40.to_csv("columnas31-40.csv")